import type { NoteLesson } from '../games/noteHunter/lessons'
import { parseNote, whiteKeysBetween } from '../music/notes'

const SMALL_KEYBOARD = { low: parseNote('C4'), high: parseNote('C5') }
const C4 = [parseNote('C4')]

export const RHYTHM_LESSONS: NoteLesson[] = [
  {
    id: 'rhythm-1',
    kind: 'rhythm',
    title: 'Dörtlükler',
    description: 'Her vuruşta bir kez bas',
    clef: 'treble',
    notes: C4,
    length: 0,
    keyboard: SMALL_KEYBOARD,
    rhythm: { bpm: 70, beatsPerBar: 4, bars: 4, values: ['q'], anyKey: true },
  },
  {
    id: 'rhythm-2',
    kind: 'rhythm',
    title: 'İkilikler',
    description: 'İki vuruş süren notalar',
    clef: 'treble',
    notes: C4,
    length: 0,
    keyboard: SMALL_KEYBOARD,
    rhythm: { bpm: 72, beatsPerBar: 4, bars: 4, values: ['q', 'h'], anyKey: true },
  },
  {
    id: 'rhythm-dino-1',
    kind: 'dino',
    title: 'Dino Koşusu',
    description: 'Engel vuruşa geldiğinde bas, Dino zıplasın',
    clef: 'treble',
    notes: C4,
    length: 0,
    keyboard: SMALL_KEYBOARD,
    rhythm: { bpm: 80, beatsPerBar: 4, bars: 6, values: ['q', 'h'], anyKey: true },
  },
  {
    id: 'rhythm-3',
    kind: 'rhythm',
    title: 'Sekizlikler',
    description: 'Bir vuruşta iki nota',
    clef: 'treble',
    notes: C4,
    length: 0,
    keyboard: SMALL_KEYBOARD,
    rhythm: { bpm: 66, beatsPerBar: 4, bars: 4, values: ['q', 'e'], anyKey: true },
  },
  {
    id: 'rhythm-4',
    kind: 'rhythm',
    title: 'Esler',
    description: 'Susmak da ritmin parçası',
    clef: 'treble',
    notes: C4,
    length: 0,
    keyboard: SMALL_KEYBOARD,
    rhythm: { bpm: 72, beatsPerBar: 4, bars: 4, values: ['q', 'h', 'qr'], anyKey: true },
  },
  {
    id: 'rhythm-drum-1',
    kind: 'drum',
    title: 'Ritim Davulcusu',
    description: 'Do, Mi ve Sol davullarını vuruşunda çal',
    clef: 'treble',
    notes: ['C4', 'E4', 'G4'].map(parseNote),
    length: 0,
    keyboard: SMALL_KEYBOARD,
    rhythm: { bpm: 76, beatsPerBar: 4, bars: 6, values: ['q', 'h', 'qr'] },
  },
  {
    id: 'rhythm-dino-2',
    kind: 'dino',
    title: 'Dino Koşusu: Notalı',
    description: 'Engellerdeki notayı vuruşunda çal',
    clef: 'treble',
    notes: whiteKeysBetween(parseNote('C4'), parseNote('G4')),
    length: 0,
    keyboard: SMALL_KEYBOARD,
    rhythm: { bpm: 70, beatsPerBar: 4, bars: 6, values: ['q', 'h', 'qr'] },
  },
  {
    id: 'rhythm-5',
    kind: 'rhythm',
    title: 'Karışık Ritim',
    description: 'Dörtlük, ikilik, sekizlik ve es bir arada',
    clef: 'treble',
    notes: C4,
    length: 0,
    keyboard: SMALL_KEYBOARD,
    rhythm: { bpm: 76, beatsPerBar: 4, bars: 4, values: ['q', 'h', 'e', 'qr'], anyKey: true },
  },
  {
    id: 'rhythm-drum-2',
    kind: 'drum',
    title: 'Davulcu: Sekizlikler',
    description: 'Hızlanan davul partisi',
    clef: 'treble',
    notes: ['C4', 'E4', 'G4'].map(parseNote),
    length: 0,
    keyboard: SMALL_KEYBOARD,
    rhythm: { bpm: 84, beatsPerBar: 4, bars: 6, values: ['q', 'e', 'qr'] },
  },
  {
    id: 'rhythm-waltz',
    kind: 'rhythm',
    title: 'Üç Dörtlük',
    description: 'Vals ölçüsü: bir, iki, üç',
    clef: 'treble',
    notes: C4,
    length: 0,
    keyboard: SMALL_KEYBOARD,
    rhythm: { bpm: 84, beatsPerBar: 3, bars: 4, values: ['q', 'h', 'hd'], anyKey: true },
  },
  {
    id: 'rhythm-dino-waltz',
    kind: 'dino',
    title: 'Dino Valsi',
    description: 'Üç dörtlükte zıpla, eslerde dur',
    clef: 'treble',
    notes: C4,
    length: 0,
    keyboard: SMALL_KEYBOARD,
    rhythm: { bpm: 90, beatsPerBar: 3, bars: 6, values: ['q', 'h', 'qr'], anyKey: true },
  },
  {
    id: 'rhythm-dotted',
    kind: 'rhythm',
    title: 'Noktalı Dörtlük',
    description: 'Bir buçuk vuruş, sonra bir sekizlik',
    clef: 'treble',
    notes: C4,
    length: 0,
    keyboard: SMALL_KEYBOARD,
    rhythm: { bpm: 66, beatsPerBar: 4, bars: 4, values: ['q', 'qd'], anyKey: true },
  },
  {
    id: 'rhythm-drum-dotted',
    kind: 'drum',
    title: 'Davulcu: Noktalılar',
    description: 'Noktalı dörtlükleri Do, Mi ve Sol ile çal',
    clef: 'treble',
    notes: ['C4', 'E4', 'G4'].map(parseNote),
    length: 0,
    keyboard: SMALL_KEYBOARD,
    rhythm: { bpm: 72, beatsPerBar: 4, bars: 6, values: ['q', 'qd', 'h'] },
  },
]
